### ISSUE TITLE
No Discord-Support

### ISSUE THREAD

**Issue by bloedboemmel** [RainerWein/menser#1]
![Discord Memes are the...](https://img.wattpad.com/8b498260f52465027fbacb70547c37bbaad9ee7d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f356d676474516644616e475968773d3d2d3931323332393032382e313631643139366233303962343061323935353033303232343833372e6a7067?s=fit&w=720&h=720)

**Comment by rainerwein** [comment]
Kommt übermorgen die Alpha 0.1a
